version: "3.9"

services:
  db:
    image:  postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pgadmin:
    image:  dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=dsaviossantos@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=dsaviossantos
    ports:
      - "80:80"
    depends_on:
      - db